openapi: 3.0.3
info:
  title: STD24001
  description: specification  STD24001
  version: 1.0.0
servers:
  - url: http://localhost:8000

paths:
  /ping:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: "pong"

  /cars:
    get:
      summary: Get all cars
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
    post:
      summary: Create one or more cars
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Car'
      responses:
        '201':
          description: Cars created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCarsResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
